"""Regenerate data/pokemon.json for ALL 94 mons from the cached unite-db data.

unite-db.com/stats.json gives current per-level stats (validated == Game8, e.g. Pikachu
Lv6 Def 80). unite-db.com/pokemon.json gives role/damage_type. We emit our existing
pokemon.json schema so stats.base_stats() works unchanged, now with attack_speed & crit
per level included.
"""
import json
import os
import re

DATA = os.path.join(os.path.dirname(__file__), os.pardir, "data")


def key(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(name).lower()).strip("_")


def role_of(meta: dict):
    tags = meta.get("tags")
    if isinstance(tags, dict):
        return tags.get("role") or tags.get("class") or tags.get("style")
    if isinstance(tags, list) and tags:
        return tags[0]
    return meta.get("role")


def main():
    stats = json.load(open(os.path.join(DATA, "unite_db_stats.json"), encoding="utf-8"))
    meta_by_key = {key(p["name"]): p for p in json.load(open(os.path.join(DATA, "unite_db_pokemon.json"), encoding="utf-8"))}

    out = {"_meta": {
        "source": "unite-db.com stats.json (per-level stats) + pokemon.json (role/damage_type)",
        "validated": "matches Game8 current values (Pikachu Lv6 Def 80, Lv15 Atk 290)",
        "note": "Regenerated by build_pokemon_from_unitedb.py. attack_speed & crit are base per-level.",
    }}
    for p in stats:
        k = key(p["name"])
        meta = meta_by_key.get(k, {})
        sbl = {}
        for lvl in p.get("level", []):
            sbl[str(lvl["level"])] = {
                "hp": lvl["hp"], "attack": lvl["attack"], "defense": lvl["defense"],
                "sp_atk": lvl["sp_attack"], "sp_def": lvl["sp_defense"],
                "attack_speed": lvl.get("attack_speed", 0), "crit": lvl.get("crit", 0),
            }
        out[k] = {
            "display_name": p["name"],
            "role": role_of(meta),
            "damage_type": meta.get("damage_type"),
            "basic_attack_multiplier": 1.0,
            "stats_by_level": sbl,
        }
    json.dump(out, open(os.path.join(DATA, "pokemon.json"), "w", encoding="utf-8"), indent=1)
    mons = [k for k in out if not k.startswith("_")]
    print(f"wrote pokemon.json: {len(mons)} mons")
    # validation + role diagnostic
    pk = out["pikachu"]["stats_by_level"]
    print("Pikachu Lv1:", pk["1"], "\nPikachu Lv6:", pk["6"])
    print("sample tags structure:", json.dumps(meta_by_key["pikachu"].get("tags"))[:200])
    for k in ("cinderace", "buzzwole", "zeraora", "snorlax"):
        if k in out:
            print(f"{k}: role={out[k]['role']} dtype={out[k]['damage_type']} Lv3={out[k]['stats_by_level'].get('3')}")


if __name__ == "__main__":
    main()
